name: Executar Pipeline JS

on:
  push:
    branches:
      - main 

  schedule:
    - cron: '0 0 * * *'

jobs:
  executar_script:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Instalar Dependências
        run: npm install  

      - name: Executar o Script do Pipeline
        run: node seu_script_de_coleta.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}